### PR TITLE
[WIP] Particles background wait for service worker

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
This PR illustrates a peculiar error encountered while running the tests in Puppeteer. Apparently, the service worker is not activated properly before we try to refresh the page in offline mode, which causes the test to fail. Chris wrote a function that, in theory, waits for the service worker to be registered and activated before continuing. However, we have discovered that even after the activated flag is on, the service worker is still not running properly.

### CODE REVIEW

**Comment by marcoow** [comment]
Hm, which change is causing this to fail though? The addition of this line? https://github.com/simplabs/breethe-client/pull/103/files#diff-125b6f7311948123630724d4ad7121acR10

**Comment by jorgelainfiesta** [comment]
Not exactly. The tests fail if this line is executed: https://github.com/simplabs/breethe-client/blob/particles-background-wait-sw/src/ui/components/FogBackground/particle.ts#L34

**Comment by marcoow** [comment]
Ah sorry - only now realized this is not against `master`…

**Comment by jorgelainfiesta** [comment]
Yeah, I just wanted to isolate this very specific issue so we can discuss it further and maybe find solutions.

**Comment by marcoow** [comment]
Did you try with puppeteer in headful mode to inspect what's going on?

**Comment by jorgelainfiesta** [comment]
Yes, we tried intensively but don't have much useful insight.

**Comment by mansona** [comment]
So just to give my own summary as to what the issue is: essentially this is an **intermittent** bug that is most likely to do with timing 😞 

The first thing that is odd is that the "waitUntil" setting for this line was **always** causing this test to fail: https://github.com/simplabs/breethe-client/pull/103/files#diff-95718d12e2a0fb30039d12108372a340L28 which I took to mean that the network never settles down (but I'm not sure why).

Through our investigation with headful mode we learned a few things: firstly if you put a 10 second wait (instead of the waitFor network) before setting offline mode and refreshing it worked 100% of the time. If you brought that down to 1 second wait it would work 90% of the time and if you made it 500ms it would almost be 50/50 test passing and test failing.

This is where we started building the `waitForAllServiceWorkers` https://github.com/simplabs/breethe-client/pull/103/files#diff-95718d12e2a0fb30039d12108372a340R4 . The first implementation just waited for the `length` of registrations to not be 0 using `navigator.serviceWorker.getRegistrations()` but this still made the test 404 on refresh as if the service worker wasn't active.

The next thing we did was we essentially kept waiting for all the registrations to have a "status" of activated https://github.com/simplabs/breethe-client/pull/103/files#diff-95718d12e2a0fb30039d12108372a340R13 assuming that if the service worker had a status of activated when you then refreshed it would be active (I don't think this is an unreasonable assumption 😭). 

My theory of how we could "fix" this is as follows:

1. Disable the "wait for network" of these tests (I'm not sure why)
1. Use our waitForAllServiceWorkers
1. Add an extra 100ms wait *after* all service workers have a status of registered as a "buffer window" 

I think this will pass the tests but I'm not sure I like it as the "best" solution 🤔 

Maybe we can have a call to discuss at some point?

**Comment by jorgelainfiesta** [comment]
Your 'fix' make the test pass consistently so I think we should stick to that. It's not entirely desirable that we do not understand completely the issue that causes the odd timing but the solution is at max going to take a few extra ms than what it needs (worst case scenario, >100ms).

**Pull request merged**
